server:
  port: 9999
  servlet:
    context-path: /typing-service
spring:
  application:
    name: typing-service
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  cloud:
    nacos:
      discovery:
        server-addr: https://nacos.tyu.wiki
        enabled: true
        register-enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://remotehost:3307/liubility?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 951753
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: remotehost
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
      shutdown-timeout: 100ms
    password:
    port: 9736
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  type-enums-package: org.liubility.typing.server.constant
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: org.liubility.typing.server.domain.entity.*
  global-config:
    db-config: #实体类字段上加上@TableLogic注解
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

jwt:
  expirationTime: 86400000
  secretKey: ${JWT_SECRET}

secret: ${MD5_SECRET}
minio:
  host: 192.168.1.150
  port: 9000
  access-key: minioadmin
  secret-key: minioadmin

cl-db:
  host: ${CL_DB_HOST}
  port: ${CL_DB_PORT}
  user: ${CL_DB_USER}
  password: ${CL_DB_PSW}
  syn-open: true
